language: python
sudo: false
python:
- 2.7
cache:
  pip: true
  directories:
  - eggs
  - downloads
install:
- virtualenv -p `which python` .
- bin/pip install -r requirements.txt
- bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
- bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C bin
- export PATH=$(pwd)/bin:$PATH
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script: bin/test
